### ISSUE TITLE
Cant import the .CSV "btw13_kerg.csv"

### ISSUE THREAD

**Issue by Wissenberg** [Lukas2112/btw-dab-proj#1]
Error:

SQL Error (2000): Load data local infile forbidden

Code:
-- Importtabelle btw2013 csv-Daten importieren
LOAD DATA LOCAL INFILE 'C:/Users/Cedric/Desktop/Mysql/btw13_kerg.csv'
 INTO TABLE import_btw2013
 CHARACTER SET latin1
 FIELDS
  TERMINATED BY ';'
 LINES
  TERMINATED BY '\n'
 IGNORE 8 LINES
;

**Comment by Lukas2112** [comment]
I will have a look at it immediately!

**Comment by Lukas2112** [comment]
Maybe [this thread](https://github.com/Agence-DnD/PIMGento-2/issues/1) is helpful?!

**Comment by Lukas2112** [comment]
SHOW GLOBAL VARIABLES LIKE 'local_infile';

**Comment by Wissenberg** [comment]
It shows me local_infile = on

**Comment by Wissenberg** [comment]
So i tried to execute the file in the console in xampp. It works so i guess it is an issue from Heidisql.
